# Generated by Django 2.0.1 on 2018-04-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dailytask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_id', models.CharField(blank=True, max_length=50)),
                ('task_id', models.CharField(blank=True, max_length=50)),
                ('task_name', models.CharField(max_length=50)),
                ('task_type', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=255)),
                ('date', models.CharField(blank=True, max_length=100)),
                ('username', models.CharField(blank=True, max_length=50)),
                ('assigned', models.CharField(blank=True, max_length=50)),
                ('status', models.IntegerField(blank=True)),
            ],
        ),
    ]
